/**
 * Event Log — canonical event types.
 *
 * The Event Log is the immutable source of truth of what happened in a Koi
 * session. Every actor (user, agent, system) emits typed events; the log is
 * append-only JSONL. Memory derived from the log lives in the Ori vault and
 * can always be regenerated by replaying.
 *
 * Adding a new type:
 *   1. Add the constant here.
 *   2. Document its `payload` shape in the JSDoc.
 *   3. Update `KNOWN_TYPES` (used for runtime validation).
 *
 * Types are strings (not enum) so unknown future types are parse-tolerant.
 */

/** User typed something into the conversation.
 *  payload: { content: string, attachments?: any[] } */
export const UserMessage = 'UserMessage';

/** An agent decided on a plan / next step.
 *  payload: { reasoning: string, next?: string } */
export const AgentPlanned = 'AgentPlanned';

/** Coordinator (or another agent) delegated work to a subagent.
 *  payload: { target: string, task: string, args?: object } */
export const AgentDelegated = 'AgentDelegated';

/** A tool was invoked.
 *  payload: { name: string, args: object } */
export const ToolCalled = 'ToolCalled';

/** A tool returned a result (success or error).
 *  payload: { name: string, ok: boolean, result?: any, error?: string } */
export const ToolResultReceived = 'ToolResultReceived';

/** A file was read by an agent.
 *  payload: { path: string, bytes: number } */
export const FileRead = 'FileRead';

/** A file was edited / written.
 *  payload: { path: string, op: 'write'|'edit'|'delete', diff?: string } */
export const FileEdited = 'FileEdited';

/** A shell command was executed.
 *  payload: { cmd: string, exit: number, stdout?: string, stderr?: string } */
export const CommandExecuted = 'CommandExecuted';

/** A non-trivial decision was made (architecture, approach, tradeoff).
 *  payload: { decision: string, alternatives?: string[], confidence?: number } */
export const DecisionMade = 'DecisionMade';

/** An error was observed (at any layer).
 *  payload: { source: string, message: string, recoverable: boolean } */
export const ErrorObserved = 'ErrorObserved';

/** A new memory note was created in the vault.
 *  payload: { title: string, type: string, scope: 'project'|'self'|'global',
 *             source_events?: string[] } */
export const MemoryWritten = 'MemoryWritten';

/** An existing memory note was updated (status change, supersede, link add).
 *  payload: { title: string, change: object } */
export const MemoryUpdated = 'MemoryUpdated';

/** A retrieve() call was made and returned scored results.
 *  payload: { query: string, filter?: object, results: Array<{title, score}>,
 *             agent: string } */
export const MemoryRetrieved = 'MemoryRetrieved';

/** A task delegated earlier completed.
 *  payload: { task: string, ok: boolean, artifacts?: string[] } */
export const TaskCompleted = 'TaskCompleted';

/** Set of all known types — used for warnings on unknown emissions. */
export const KNOWN_TYPES = new Set([
  UserMessage,
  AgentPlanned,
  AgentDelegated,
  ToolCalled,
  ToolResultReceived,
  FileRead,
  FileEdited,
  CommandExecuted,
  DecisionMade,
  ErrorObserved,
  MemoryWritten,
  MemoryUpdated,
  MemoryRetrieved,
  TaskCompleted,
]);
